### ISSUE TITLE
Allow carrierwave 2.1

### ISSUE THREAD

**Issue by andreas-venturini** [denkungsart/carrierwave_backgrounder#1]
https://github.com/carrierwaveuploader/carrierwave/blob/master/CHANGELOG.md#210---2020-02-16

context: https://github.com/denkungsart/castupload/pull/4999

**Comment by fschwahn** [comment]
I removed the commit again from master, as I noticed that carrierwave 2.1 is already allowed with the latest commit on master. I didn't test this, as prestage & castupload are still on carrierwave 1.x, but looking at the changelog I cannot imagine anything breaking because of this change.

**Comment by andreas-venturini** [comment]
>  I didn't test this, as prestage & castupload are still on carrierwave 1.x

We need to test this, starting w/ Castupload, I will open an issue for it.
